export const RICHFIELD_ADMIN_COPY = {
  account: {
    description: "You can edit the website and choose what visitors can see.",
    signOut: "Sign out",
    signedIn: "Signed in",
    viewSite: "View site",
  },
  actions: {
    cancel: "Cancel",
    delete: "Delete",
    keep: "Keep it",
    newArticle: "New article",
    newBrand: "New brand",
    newContactChannel: "New channel",
    newContactForm: "New form configuration",
    newContactPage: "New contact page",
    newContactSubmission: "New message",
    newImage: "New image",
    newJob: "New job",
    newLeader: "New leader",
    newMilestone: "New milestone",
    save: "Save",
    saving: "Saving",
  },
  dashboard: {
    eyebrow: "Richfield",
    subtitle:
      "Manage brands, contacts, careers, images, leadership, and milestones in one calm place.",
    title: "Richfield Dashboard",
  },
  editor: {
    basics: "Basics",
    details: "Details",
    discardChanges: "Discard changes",
    image: "Image",
    imageHelp: "Choose a clear picture visitors will recognize.",
    keepEditing: "Keep editing",
    openPreview: "Open preview",
    publicView: "Visitor view",
    saved: "Saved.",
    steps: {
      basics: {
        description: "Title, link, and visibility",
        label: "Basics",
      },
      danger: {
        description: "Remove this item",
        label: "Remove",
      },
      details: {
        description: "Country, timing, and summary",
        label: "Details",
      },
      image: {
        description: "Cover and image details",
        label: "Cover",
      },
      writing: {
        description: "Long-form body copy",
        label: "Writing",
      },
    },
    unsavedDescription:
      "You have changes that have not been saved yet. Keep editing or discard them before closing.",
    unsavedHeading: "Close without saving?",
    unsavedTitle: "Unsaved changes",
    visibility: "Visibility",
  },
  empty: {
    articles: "Publish the first story, market note, or company update.",
    brands: "Add the first brand from the editor.",
    contactChannels: "Add the first public contact channel from the editor.",
    contactForm: "Configure the public contact form and delivery routing.",
    contactPage: "Add contact page content from the editor.",
    contactSubmissions: "No contact messages have been saved yet.",
    images: "Add the first reusable image from the editor.",
    jobs: "Add the first open role from the editor.",
    leadership: "Add the first leader from the editor.",
    milestones: "Add the first milestone from the editor.",
  },
  errors: {
    delete: "We could not delete this item. Please try again.",
    save: "We could not save this item. Please try again.",
  },
  members: {
    description:
      "See who can help edit this site. Manage invitations and access in Tuturuuu.",
    empty: "No team members were returned.",
    loading: "Loading team members...",
    manage: "Manage in Tuturuuu",
    title: "Team members",
    unavailable: "Team members are not available right now.",
  },
  publish: {
    check: "Check for changes",
    description:
      "Review what changed, then share the latest version with visitors.",
    done: "Your website is up to date.",
    force: "Share anyway",
    pending: "changes ready",
    push: "Share latest version",
    title: "Publish",
    warning: "Some changes need one more confirmation.",
  },
  storage: {
    back: "Back",
    chooseFile: "Choose file",
    createFolder: "New folder",
    deleteDone: "Removed.",
    deleteHint:
      "This also clears it from any brand, leader, or milestone using it.",
    description:
      "See how much room your images and downloads are using.",
    driveDescription:
      "Open Tuturuuu Drive for deeper file management, sharing, and team folders.",
    driveLink: "Open Tuturuuu Drive",
    emptyFiles: "No files in this spot yet.",
    files: "Files",
    folderDone: "Folder added.",
    folderName: "Folder name",
    heading: "File room",
    largest: "Largest file",
    limit: "Plan limit",
    noFiles: "No files have been added yet.",
    of: "of",
    open: "Open",
    refresh: "Refresh",
    remove: "Remove",
    rename: "Rename",
    renameDone: "Renamed.",
    root: "Main room",
    upload: "Upload",
    uploadDone: "Uploaded.",
    uploadHelp: "Choose the same name to replace an existing file.",
    smallest: "Smallest file",
    title: "Storage",
    unavailableTitle: "Storage details are unavailable",
    unknownDate: "Date unavailable",
    used: "Used",
  },
  tabs: {
    account: "Account",
    articles: "Insights",
    brands: "Brands",
    contactChannels: "Channels",
    contactForm: "Form fields",
    contactPage: "Contact page",
    // Previously "Contact" as well, which put two identically-labelled tabs in
    // the same bar with no way to tell them apart.
    contactSubmissions: "Responses",
    gallery: "Gallery",
    images: "Gallery",
    jobs: "Jobs",
    leadership: "Leadership",
    members: "Members",
    milestones: "Milestones",
    publish: "Publish",
    storage: "Storage",
  },
  // Thirteen flat tabs read as undifferentiated soup. These group them into
  // scannable areas so an editor can find a surface without reading every label.
  tabGroups: {
    contact: "Contact",
    content: "Content",
    media: "Media",
    team: "Team",
  },
  visibility: {
    archived: "Hidden",
    draft: "Draft",
    published: "Live",
    scheduled: "Scheduled",
  },
} as const;
